Repository arrow-kt/arrow, pull requests merged in 2021-03, with the labels that each got.

#2265 Ank: clean macros
  arrow-libs/ank/README.md
  arrow-libs/ank/arrow-ank/src/main/kotlin/arrow/ank/algebra.kt
  arrow-libs/ank/arrow-ank/src/main/kotlin/arrow/ank/ank.kt
  arrow-libs/ank/arrow-ank/src/main/kotlin/arrow/ank/interpreter.kt
Labels: 0.12.0

#2267 Remove redundant SuspendConnection
  arrow-libs/ank/settings.gradle
  arrow-libs/fx/arrow-fx-coroutines-test/build.gradle
  arrow-libs/fx/arrow-fx-coroutines/build.gradle
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Bracket.kt
  arrow-libs/fx/arrow-fx-suspend-connection/build.gradle
  arrow-libs/fx/arrow-fx-suspend-connection/gradle.properties
  arrow-libs/fx/arrow-fx-suspend-connection/src/main/kotlin/arrow/fx/coroutines/SuspendConnection.kt
  arrow-libs/fx/arrow-fx-suspend-connection/src/test/kotlin/arrow/fx/coroutines/SuspendConnectionTests.kt
  arrow-libs/fx/settings.gradle
  arrow-libs/settings.gradle
Labels: 0.13.0

#2275 Remove Higher Kinded Types
  arrow-libs/core/arrow-annotations/src/main/java/arrow/extension.kt
  arrow-libs/core/arrow-annotations/src/main/java/arrow/higherkind.kt
  arrow-libs/core/arrow-annotations/src/main/java/arrow/hkjs.kt
  arrow-libs/core/arrow-annotations/src/main/java/arrow/hks.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/AndThen.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Const.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Eval.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/FunctionK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Hashed.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/MapK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SequenceK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SetK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SortedMapK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple10.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple2.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple3.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple4.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple5.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple6.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple7.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple8.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple9.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/TupleN.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Monoid.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/Kind.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/Try.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/core/extensions/AnnotatedInstance.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/core/extensions/AnnotationInfo.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/core/extensions/ExtensionProcessor.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/core/extensions/PolyTemplateGenerator.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/higherkinds/AnnotatedHigherKind.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/higherkinds/AnnotationInfo.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/higherkinds/HigherKindsFileGenerator.kt
  arrow-libs/core/arrow-meta/src/main/java/arrow/higherkinds/HigherKindsProcessor.kt
Labels: 0.13.0

#2276 Undeprecate Option data type
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
Labels: 0.12.0

#2278 Cu f31fp2 unify constructors
  arrow-libs/core/arrow-continuations/src/test/kotlin/generic/SuspendingComputationTest.kt
  arrow-libs/core/arrow-continuations/src/test/kotlin/generic/TestSuite.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/AndThen.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Eval.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/MapK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SequenceK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/computations/either.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/computations/validated.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/EitherTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/ValidatedTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/typeclasses/TraverseTest.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/Try.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt
  arrow-libs/core/arrow-meta/arrow-meta-test-models/src/main/java/arrow/ap/objects/iso/IsoSealed.kt
  arrow-libs/core/arrow-meta/arrow-meta-test-models/src/main/java/arrow/ap/objects/lens/LensSealed.kt
  arrow-libs/core/arrow-meta/arrow-meta-test-models/src/main/java/arrow/ap/objects/optional/OptionalSealed.kt
  arrow-libs/core/arrow-meta/arrow-meta-test-models/src/main/java/arrow/ap/objects/prism/Prism.kt
  arrow-libs/core/arrow-meta/arrow-meta-test-models/src/main/java/arrow/ap/objects/prism/PrismWithoutCompanion.kt
  arrow-libs/examples/src/test/kotlin/arrow/DataTypeExamples.kt
  arrow-libs/fx/arrow-fx-coroutines-test/src/main/kotlin/arrow/fx/coroutines/predef-test.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/CircuitBreaker.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Race2.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Resource.kt
  arrow-libs/optics/arrow-optics/src/main/kotlin/arrow/optics/Prism.kt
  arrow-libs/optics/arrow-optics/src/main/kotlin/arrow/optics/std/option.kt
  arrow-libs/optics/arrow-optics/src/test/kotlin/arrow/optics/GetterTest.kt
  arrow-libs/optics/arrow-optics/src/test/kotlin/arrow/optics/LensTest.kt
  arrow-libs/optics/arrow-optics/src/test/kotlin/arrow/optics/OptionalTest.kt
  arrow-libs/optics/arrow-optics/src/test/kotlin/arrow/optics/std/EitherTest.kt
  arrow-site/docs/_code/core-home-code.md
  arrow-site/docs/docs/datatypes/nonemptylist/README.md
  arrow-site/docs/docs/fold/README.md
  arrow-site/docs/docs/getter/README.md
  arrow-site/docs/docs/io/README.md
  arrow-site/docs/docs/patterns/errorhandling/README.md
  arrow-site/docs/docs/patterns/monadcomprehensions/README.md
Labels: 0.13.0

#2279 Update BOM file for 0.13.0
  arrow-libs/fx/settings.gradle
  arrow-stack/build.gradle
Labels: 0.13.0

#2281 CU-9rr4w5 remove K Wrappers
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/MapK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SequenceK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SetK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/MapsTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt
  arrow-libs/optics/arrow-optics/src/main/kotlin/arrow/optics/std/map.kt
  arrow-libs/optics/arrow-optics/src/test/kotlin/arrow/optics/GetterTest.kt
  arrow-libs/optics/arrow-optics/src/test/kotlin/arrow/optics/OptionalTest.kt
  arrow-site/docs/docs/arrow/typeclasses/monoid/README.md
  arrow-site/docs/docs/optional/README.md
Labels: 0.13.0

#2286 CU-f4ywpe Fix ReplaceWith MapK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/MapK.kt
Labels: 0.12.0

#2289 Merge master into release/0.13.0
  arrow-site/docs/docs/io/README.md
  arrow-site/docs/docs/patterns/errorhandling/README.md
Labels: 0.13.0

#2288 CU-f31wbh Deprecate top-level Left & Right Either constructors
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
Labels: 0.12.0

#2291 CU-f51n03 Deprecate map2 in favor of zip in Resource.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Resource.kt
Labels: 0.12.0

#2293 CU-f31dfg Remove Tuple2 & Tuple3
  arrow-libs/ank/arrow-ank/src/main/kotlin/arrow/ank/algebra.kt
  arrow-libs/ank/arrow-ank/src/main/kotlin/arrow/ank/ank.kt
  arrow-libs/ank/arrow-ank/src/main/kotlin/arrow/ank/interpreter.kt
  arrow-libs/core/arrow-continuations/src/test/kotlin/generic/TestSuite.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SortedMapK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple2.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple3.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/TupleN.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/IterableTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/tuple.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/tupling.kt
  arrow-libs/core/arrow-syntax/src/test/kotlin/arrow/syntax/test/FunctionSyntaxTest.kt
  arrow-libs/fx/arrow-fx-coroutines-test/src/main/kotlin/arrow/fx/coroutines/ArrowFxSpec.kt
  arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/STM.kt
  arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/TMap.kt
  arrow-site/docs/docs/arrow/typeclasses/monoid/README.md
Labels: 0.13.0

#2287 CU-ez5ybx Add deprecations for Tuple2 & Tuple3 in Arrow Syntax
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/tuple.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/tupling.kt
Labels: 0.12.0

#2294 CU-f540fg Deprecate remaining tuple2 APIs
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/TupleN.kt
  arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/STM.kt
Labels: 0.12.0

#2296 Remove creation of intermediate lists in mapN
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SequenceK.kt
Labels: 0.12.0

#2285 CU-f36jg7 Docs: Revamp Monad tutorial with suspension and type checking
  arrow-site/docs/docs/patterns/monads/README.md
Labels: 0.12.0

#2298 CU-f6ydva Remove deprecated tuple params
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple10.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple4.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple5.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple6.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple7.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple8.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple9.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/TupleN.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/tuple.kt
Labels: 0.13.0

#2301 CU-f53298 Deprecate extensions and instances objects
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/ListExtensions.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/set.kt
Labels: 0.12.0

#2304 CU-f7205t Remove hashed
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Hashed.kt
Labels: 0.13.0

#2300 EitherTest#contains - check that arbitrary values aren't the same
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/EitherTest.kt
Labels: 0.12.0

#2303 CU-f726g5 Remove SortedMapK
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SortedMap.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SortedMapK.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt
Labels: 0.13.0

#2292 CU-f34dk7 remove old mapN and expose new APIs
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/List.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/MapK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Nullable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SequenceK.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/NullableTest.kt
Labels: 0.13.0

#2316 Configuration: add default region
  .github/workflows/publish_doc.yml
Labels: 0.12.0

#2319 Clean old content
  arrow-libs/fx/arrow-fx-coroutines-stream/README.MD
  arrow-libs/fx/arrow-fx-coroutines-stream/build.gradle
  arrow-libs/fx/arrow-fx-coroutines-stream/gradle.properties
Labels: 0.12.0

#2320 Configuration: remove stdlib as transitive dependency
  arrow-libs/ank/gradle.properties
  arrow-libs/core/arrow-annotations/build.gradle
  arrow-libs/core/arrow-continuations/build.gradle
  arrow-libs/core/arrow-core-data/build.gradle
  arrow-libs/core/arrow-core-retrofit/build.gradle
  arrow-libs/core/arrow-core/build.gradle
  arrow-libs/core/arrow-meta/arrow-meta-test-models/build.gradle
  arrow-libs/core/arrow-syntax/build.gradle
  arrow-libs/core/gradle.properties
  arrow-libs/fx/arrow-fx-reactor/build.gradle
  arrow-libs/fx/arrow-fx-rx2/build.gradle
  arrow-libs/fx/arrow-fx-suspend-connection/build.gradle
  arrow-libs/fx/arrow-fx/build.gradle
  arrow-libs/fx/gradle.properties
  arrow-libs/gradle.properties
  arrow-libs/optics/arrow-optics/build.gradle
  arrow-libs/optics/gradle.properties
Labels: 0.12.0

#2312 CU-fb532c - Clean up Selective api
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Selective.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/option/selective/OptionSelective.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/validated/selective/ValidatedSelective.kt
  arrow-site/docs/docs/arrow/typeclasses/selective/README.md
Labels: 0.12.0

#2310 CU-fb50p3 - Clean up Traverse API
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Foldable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Traverse.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/TraverseFilter.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/const.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/const/foldable/ConstFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/const/traverse/ConstTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/either/foldable/EitherFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/either/traverse/EitherTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/hashed/foldable/HashedFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/ior/foldable/IorFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/ior/traverse/IorTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/list/foldable/ListKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/list/traverse/ListKTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk/foldable/ListKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk/traverse/ListKTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/map/foldable/MapKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/map/traverse/MapKTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/mapk/foldable/MapKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/mapk/traverse/MapKTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/nonemptylist/foldable/NonEmptyListFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/nonemptylist/traverse/NonEmptyListTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/option.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/option/foldable/OptionFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/option/traverse/OptionTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/option/traverseFilter/OptionTraverseFilter.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequence/foldable/SequenceKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequence/traverse/SequenceKTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequencek/foldable/SequenceKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequencek/traverse/SequenceKTraverse.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/set/foldable/SetKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/setk/foldable/SetKFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/validated/foldable/ValidatedFoldable.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/validated/traverse/ValidatedTraverse.kt
Labels: 0.12.0

#2322 CU-fh306p Remove deprecated ordering
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Const.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ordering.kt
Labels: 0.13.0

#2324 CU-fh2vcf - Deprecate mapN and fix zip for collections
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/IterableTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/NonEmptyListTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/UnitSpec.kt
  arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/list/apply/ListKApply.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk/apply/ListKApply.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/nonemptylist/apply/NonEmptyListApply.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequence/apply/SequenceKApply.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequencek/apply/SequenceKApply.kt
  arrow-site/docs/docs/datatypes/nonemptylist/README.md
Labels: 0.12.0

#2326 Add deprecation to parmapn in favor of parzip
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParMapN.kt
Labels: 0.12.0

#2327 Fix Const & Either mapN deprecation
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/const/apply/ConstApply.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/either/apply/EitherApply.kt
Labels: 0.12.0

#2329 CU-fv6x6d Clean up Arrow Fx based on API Review
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Resource.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/UnsafePromise.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/startCoroutineCancellable.kt
  arrow-libs/fx/arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ResourceTest.kt
Labels: 0.12.0

#2328 CU-fv6xq2 Clean up Arrow Syntax based on API Review
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/AndThenN.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/complement.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/composition.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/currying.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/list.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/memoization.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/pairing.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/partials.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/pipe.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/reverse.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/tupling.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/list.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/complement.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/currying.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/memoization.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/pairing.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/partials.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/pipe.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/reverse.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/tupling.kt
Labels: 0.12.0

#2331 Revert partially without explicit arity
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/partials.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/partials.kt
Labels: 0.12.0

#2332 Clean-up new code & breaking changes since 0.12.0
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple3.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Applicative.kt
  arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/nonemptylist/monad/NonEmptyListMonad.kt
Labels: 0.12.0

#2333 Arrow Fx: Clean-up new code & breaking changes since 0.12.0
  arrow-libs/fx/arrow-fx-coroutines-test/src/test/kotlin/arrow/fx/coroutines/PredefTest.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ConcurrentVar.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/UnsafePromise.kt
  arrow-libs/fx/arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ConcurrentVarTest.kt
  arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/STM.kt
  arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/TMap.kt
Labels: 0.12.0

#2335 @JvmStatic companion object functions & rename new Arrow Syntax files
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Const.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Eval.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Nullable.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/EitherUsage.java
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/EvalUsage.java
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/IorUsage.java
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/NonEmptyListUsage.java
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/NullableUsage.java
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/OptionUsage.java
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/ValidatedUsage.java
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/composition.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/currying.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/memoization.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/partials.kt
  arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/tuple.kt
Labels: 0.12.0

#2338 Fix null bug in Validated#zip & Ior#zip
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/predef.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/IorTest.kt
  arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/ValidatedTest.kt
Labels: 0.12.0

#2339 Update typeclasses docs
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Monoid.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semiring.kt
  arrow-site/docs/docs/arrow/typeclasses/monoid/README.md
  arrow-site/docs/docs/arrow/typeclasses/semigroup/README.md
Labels: 0.12.0

#2323 Update Semigroup, Semiring and Monoid docs
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Monoid.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semigroup.kt
  arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semiring.kt
  arrow-site/docs/docs/arrow/typeclasses/monoid/README.md
  arrow-site/docs/docs/arrow/typeclasses/semigroup/README.md
Labels: 0.12.0

#2309 CU-fb6wcj Docs: Quickstart description changes
  arrow-site/docs/_data/sidebar-core.yml
  arrow-site/docs/docs/quickstart/README.md
Labels: 0.12.0, arrow-core, docs

#2341 Fix redundant tuple naming
  arrow-libs/optics/arrow-optics/src/main/kotlin/arrow/optics/Traversal.kt
  arrow-libs/optics/arrow-optics/src/main/kotlin/arrow/optics/std/tuple.kt
Labels: 0.12.0

#2343 Deprecate IQueue & update deprecations
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/IQueue.kt
  arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTupledN.kt
Labels: 0.12.0

#2348 Fix: update BOM file
  arrow-stack/build.gradle
Labels: 0.13.0

#2355 Fix Iso generation using letters instead of named params
  arrow-libs/core/arrow-meta/src/main/java/arrow/optics/IsosFileGenerator.kt
Labels: 0.13.0
