Repository arrow-kt/arrow, pull requests merged in 2023-03, with the labels that each got.

#2949 Option: deprecate or, orElse and unzip
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt
Labels: 1.2.0

#2954 Simplify recover, and catch APIs. Add getOrElse
  arrow-libs/core/arrow-core/api/arrow-core.api
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Effect.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/ErrorHandlers.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Mappers.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/MappersSpec.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-01.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-03.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-05.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-06.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-07.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-08.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-09.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/test/RaiseKnitTest.kt
Labels: help wanted, discussion, 1.2.0

#2956 Fix ctx inconsistency
  arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParMap.kt
Labels: 1.2.0

#2958 Update Raise.xOrAccumulate
  arrow-libs/core/arrow-core/api/arrow-core.api
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt
Labels: 1.2.0

#2935 Deprecation of `Semigroup` and `Monoid`
  arrow-libs/core/arrow-core/api/arrow-core.api
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Const.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Endo.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Ior.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptyList.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Pair.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Sequence.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/predef.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/typeclasses/Monoid.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/typeclasses/Semigroup.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/typeclasses/Semiring.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/BooleanTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EitherTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EndoTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/IorTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/ListKTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/MapKTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/NonEmptyListTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/OptionTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/SequenceKTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/extensions/NumberInstancesTest.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/IorSpec.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/Laws.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/laws/MonoidLaws.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/laws/SemigroupLaws.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/laws/SemiringLaws.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-02.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Every.kt
Labels: 1.2.0

#2905 Update Circuit Breaker & remove Arrow Fx Coroutines dependency from Resilience
  arrow-libs/fx/arrow-fx-resilience/api/arrow-fx-resilience.api
  arrow-libs/fx/arrow-fx-resilience/build.gradle.kts
  arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/CircuitBreaker.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/common/Platform.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/predef.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/CircuitBreakerTest.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/FlowTest.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/KotestConfig.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/Platform.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/SagaSpec.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/ScheduleTest.kt
  arrow-libs/fx/arrow-fx-resilience/src/jsMain/kotlin/arrow/fx/resilience/common/platform.kt
  arrow-libs/fx/arrow-fx-resilience/src/jsMain/kotlin/arrow/fx/resilience/timeInMillis.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmMain/kotlin/arrow/fx/resilience/common/platform.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmMain/kotlin/arrow/fx/resilience/timeInMillis.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-circuitbreaker-01.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-circuitbreaker-02.kt
  arrow-libs/fx/arrow-fx-resilience/src/nativeMain/kotlin/arrow/fx/resilience/common/platform.kt
  arrow-libs/fx/arrow-fx-resilience/src/nativeMain/kotlin/arrow/fx/resilience/timeInMillis.kt
Labels: arrow-fx, 1.2.0

#2946 Tracing POC
  arrow-libs/core/arrow-core/api/arrow-core.api
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Trace.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/StructuredConcurrencySpec.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/TraceSpec.kt
  arrow-libs/core/arrow-core/src/jsMain/kotlin/arrow/core/raise/CancellationExceptionNoTrace.kt
  arrow-libs/core/arrow-core/src/jvmMain/kotlin/arrow/core/raise/CancellationExceptionNoTrace.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/arrow/core/raise/TraceJvmSpec.kt
  arrow-libs/core/arrow-core/src/nativeMain/kotlin/arrow/core/raise/CancellationExceptionNoTrace.kt
Labels: help wanted, discussion, 1.2.0

#2979 New Schedule encoding for Fx Resilience
  arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api
  arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Schedule.kt
  arrow-libs/fx/arrow-fx-resilience/api/arrow-fx-resilience.api
  arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/Schedule.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/flow.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/CircuitBreakerTest.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/FlowTest.kt
  arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/ScheduleTest.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-01.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-02.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-03.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-04.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-05.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-06.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-07.kt
  arrow-libs/fx/arrow-fx-resilience/src/jvmTest/kotlin/examples/example-schedule-08.kt
Labels: 1.2.0

#2978 Add bind alias for Sequence operation in DSL
  arrow-libs/core/arrow-core/api/arrow-core.api
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/EffectSpec.kt
Labels: 1.2.0

#2985 Deprecate Monoid and Semigroup in Optics
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/typeclasses/Monoid.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/laws/MonoidLaws.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/laws/SemigroupLaws.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/laws/SemiringLaws.kt
  arrow-libs/optics/arrow-optics/api/arrow-optics.api
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Every.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Fold.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Getter.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Iso.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Lens.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Optional.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/OptionalGetter.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Prism.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Setter.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Traversal.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/predef.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/typeclasses/FilterIndex.kt
  arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/typeclasses/Index.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/EveryTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/FoldTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/GetterTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/IsoTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/LensTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/OptionalTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/PrismTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/SetterTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/TraversalTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/instances/AtInstanceTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/instances/ConsInstanceTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/instances/EitherInstanceTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/instances/FilterIndexInstanceTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/instances/IndexInstanceTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/instances/SnocInstanceTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/EitherTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/ListTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/MapTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/NonEmptyListTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/OptionTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/StringTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/TupleTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/std/ValidatedTest.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/test/laws/IsoLaws.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/test/laws/Laws.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/test/laws/LensLaws.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/test/laws/OptionalLaws.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/test/laws/PrismLaws.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/test/laws/SetterLaws.kt
  arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/test/laws/TraversalLaws.kt
Labels: 1.2.0

#2971 Deprecate Map.kt traverse & niche signatures, hygiene & bindAll
  arrow-libs/core/arrow-core/api/arrow-core.api
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/map.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt
  arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt
  arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/MapKTest.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-01.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-02.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-03.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-04.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-05.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-06.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-07.kt
  arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-map-08.kt
Labels: 1.2.0

#2957 Replace parTupled with parZipOrAccumulate
  arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api
  arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParTupled.kt
  arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParZipOrAccumulate.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-01.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-02.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-03.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-04.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-05.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-06.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-07.kt
  arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-partupled-08.kt
Labels: help wanted, discussion, 1.2.0
